### ISSUE TITLE
IfcPavement IfcCourse relation to IfcAlignment

### ISSUE THREAD

**Issue by BernhardWehrle** [buildingSMART/Sample-Test-Files#103]
When reading the alignment, I iterate through the alignment elements. 
In the same way as for example in Landxml.
I read the HorizontalAlignment, and maybe the VericalAlignment and the Crosssection.

When I go through the decomposed container (IfcRelNests) of the alignment in IFC4.3,
I have the horizontal vertical and cant alignment but no cross section.

My question is.
Can I add the IfcCourse and IFCPavement objects to the decomposed container 
when exporting an alignment?

Otherwise it is not easy to get a conaction to IfcPavement or IfcCourse 
when I am in the semanitc part of the alignment (in the import part).

**Comment by pjanck** [comment]
IMHO, an alignment does not need a cross section to be a valid alignment. The cross section is used by the pavement / rails / other geometries extruded along the alignment.

I would connect an `IfcCourse` with an `IfcAlignment` using the `IfcRelPositions` relationship at export since it is positioned along it. Both should be included in the spatial structure somewhere (e.g. in `IfcRoad`).

The other (complementary) suggestion (currently in the discussion here: https://github.com/buildingSMART/IFC4.3.x-development/issues/10 ) is to connect the alignment geometry back to the semantic part using an INVERSE to allow this sort of graph walking.

**Comment by pjanck** [comment]
We're moving to the new repository. If you're still having difficulties, be sure to open a new issue there: https://github.com/bSI-InfraRoom/IFC-infra-unit-test
