### ISSUE TITLE
ifc4x3 test files are using not release schema

### ISSUE THREAD

**Issue by Andrej730** [buildingSMART/Sample-Test-Files#139]
ifc4x3 test files in https://github.com/buildingSMART/Sample-Test-Files/tree/master/IFC%204.3 are using ifc4x3_rc2 instead of the release schema which is less likely to be supported by the software working with IFC.

Relalted https://github.com/IfcOpenShell/IfcOpenShell/issues/5694

**Comment by berlotti** [comment]
yeah... this repo has a long history of not being very well maintained. 
We knew there were some problems, but diving into it this morning it turns out even worse than I thought. 

I've purged the history (way too many zip files) and moved it to https://github.com/buildingsmart-community/Community-Sample-Test-Files

This repo will also be purged and we will publish valid and official examples here later.
