### ISSUE TITLE
Storylines vs unit tests

### ISSUE THREAD

**Issue by larswik** [buildingSMART/Sample-Test-Files#54]
Some things from discussion with Finnish storyline (dealing with "doing the right things"):
1. Storyline authors may need access to GitHub (commenting pull requests, registering issues)
2. If there is an explicit connection between a Storyline/ES and a unit test, can we make this connection explicit in the unit test description? =>Add this to the template.
3. Storylines authors should then be assigned to pull requests regarding their storyline.

**Comment by pjanck** [comment]
ad 1. Yes, gladly. Send the usernames to me so that I can give them rights. We need to address this during our next expert panel.

ad 2. Good point. This connection should be explicit, it enables easier checking among other things. Will expand the unit test template.

ad 3. We need to put their GitHub usernames in the Miro board for everyone to link as appropriate. Action for the next expert panel.
