### ISSUE TITLE
Improving IFC documentation - diagrams of the IFC entities hierarchy

### ISSUE THREAD

**Issue by blaz-p** [buildingSMART/Sample-Test-Files#90]
We have a problem with how to specify the position of the IFC entity in the structure (the hierarchy above it).

For example, if we want to write Terrain surface using `IfcTriangulatedIrregularNetwork`, how can we know who is his parent.
How can we know that `IfcTriangulatedIregularNetwork` is a child of `IfcSolidStratum` and `IfcSolidStratum` is a child of `IfcElement Assembly`?
It would be very useful to have in the documentation diagrams of the tree structure for IfcEntities or something like that.
If such diagrams already exist, please let me know.

**Comment by pjanck** [comment]
For context, see #69 .

**Comment by AlexBrad1ey** [comment]
Not Quite sure what the issue is here... But I'll give it a go.
> It would be very useful to have in the documentation diagrams of the tree structure for IfcEntities or something like that.

Firstly no instance diagrams exist yet for the new stratum entities this is something that can be done to help.

> How can we know that IfcTriangulatedIregularNetwork is a child of IfcSolidStratum and IfcSolidStratum is a child of IfcElement Assembly?

This should be achieved through the use of the inverse Relationships which allow you to track back up the spatial hierarchy. p[lease note `IfcXXStratum`s should be grouped in geotechnical assemblies which is a specfic and different element to `IfcElementAssembly`.
If your looking for a correct simple use of the new Stratum then see the Tin_1 through Tin_4 UTs which provide the rep of the structure.

**Comment by pjanck** [comment]
@blaz-p : Did the answer by @AlexBrad1ey help you resolve your issue? If so, please consider closing the issue. Otherwise please provide additional questions/information.

**Comment by blaz-p** [comment]
Thank you @AlexBrad1ey for the explanation. I will close this issue and I think also Pull Request #69 could be closed.
